twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    exception_controller: null
    globals:
        upload_image_directory: '/assets/uploads/images/'
        text_answer_min_lenght: '%text_answer_min_lenght%'
        without_header_routes: '%without_header_routes%'
        domain: '%domain%'

when@test:
    twig:
        strict_variables: true
